<?php return array(
    'root' => array(
        'name' => 'codeinwp/visualizer',
        'pretty_version' => 'v4.0.2',
        'version' => '4.0.2.0',
        'reference' => 'cb4934b0a64c44f3a01921a3c0e41fe7d4fac2b8',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'codeinwp/themeisle-sdk' => array(
            'pretty_version' => '3.3.52',
            'version' => '3.3.52.0',
            'reference' => 'd1ae68cbd4f84934b4d982e9eeff317b9f4c814a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeinwp/themeisle-sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'codeinwp/visualizer' => array(
            'pretty_version' => 'v4.0.2',
            'version' => '4.0.2.0',
            'reference' => 'cb4934b0a64c44f3a01921a3c0e41fe7d4fac2b8',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neitanod/forceutf8' => array(
            'pretty_version' => 'v2.0.4',
            'version' => '2.0.4.0',
            'reference' => 'c1fbe70bfb5ad41b8ec5785056b0e308b40d4831',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neitanod/forceutf8',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'openspout/openspout' => array(
            'pretty_version' => 'v3.7.4',
            'version' => '3.7.4.0',
            'reference' => 'dfbbd53b5edcd486b45a37f6a04fac33073c70f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../openspout/openspout',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woocommerce/action-scheduler' => array(
            'pretty_version' => '3.9.3',
            'version' => '3.9.3.0',
            'reference' => 'c58cdbab17651303d406cd3b22cf9d75c71c986c',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../woocommerce/action-scheduler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
